In [ ]:
  #DATA LOAD

In [196]:
import pandas as pd
import numpy as np
import tensorflow as tf

car_dataset = pd.read_csv('/content/drive/MyDrive/AI - DEEP LEARNING ASSIGNMENTS/CarPrice_Assignment.csv')

In [197]:
car_dataset.head()

   car_ID  symboling                   CarName  ... citympg highwaympg    price
0       1          3        alfa-romero giulia  ...      21         27  13495.0
1       2          3       alfa-romero stelvio  ...      21         27  16500.0
2       3          1  alfa-romero Quadrifoglio  ...      19         26  16500.0
3       4          2               audi 100 ls  ...      24         30  13950.0
4       5          2                audi 100ls  ...      18         22  17450.0

[5 rows x 26 columns]

In [ ]:
 #Missing Values

In [198]:
car_dataset.isnull

<bound method DataFrame.isnull of      car_ID  symboling                   CarName  ... citympg highwaympg    price
0         1          3        alfa-romero giulia  ...      21         27  13495.0
1         2          3       alfa-romero stelvio  ...      21         27  16500.0
2         3          1  alfa-romero Quadrifoglio  ...      19         26  16500.0
3         4          2               audi 100 ls  ...      24         30  13950.0
4         5          2                audi 100ls  ...      18         22  17450.0
..      ...        ...                       ...  ...     ...        ...      ...
200     201         -1           volvo 145e (sw)  ...      23         28  16845.0
201     202         -1               volvo 144ea  ...      19         25  19045.0
202     203         -1               volvo 244dl  ...      18         23  21485.0
203     204         -1                 volvo 246  ...      26         27  22470.0
204     205         -1               volvo 264gl  ...      19         25  22625.0

[205 rows x 26 columns]>

In [199]:
 np.where(pd.isnull(car_dataset))

(array([], dtype=int64), array([], dtype=int64))

In [200]:
car_dataset.isnull().any()

car_ID              False
symboling           False
CarName             False
fueltype            False
aspiration          False
doornumber          False
carbody             False
drivewheel          False
enginelocation      False
wheelbase           False
carlength           False
carwidth            False
carheight           False
curbweight          False
enginetype          False
cylindernumber      False
enginesize          False
fuelsystem          False
boreratio           False
stroke              False
compressionratio    False
horsepower          False
peakrpm             False
citympg             False
highwaympg          False
price               False
dtype: bool

In [201]:
car_dataset.dtypes

car_ID                int64
symboling             int64
CarName              object
fueltype             object
aspiration           object
doornumber           object
carbody              object
drivewheel           object
enginelocation       object
wheelbase           float64
carlength           float64
carwidth            float64
carheight           float64
curbweight            int64
enginetype           object
cylindernumber       object
enginesize            int64
fuelsystem           object
boreratio           float64
stroke              float64
compressionratio    float64
horsepower            int64
peakrpm               int64
citympg               int64
highwaympg            int64
price               float64
dtype: object

In [202]:
car_dataset.drop(columns=['car_ID'], inplace= True)

In [203]:
car_dataset.columns

Index(['symboling', 'CarName', 'fueltype', 'aspiration', 'doornumber',
       'carbody', 'drivewheel', 'enginelocation', 'wheelbase', 'carlength',
       'carwidth', 'carheight', 'curbweight', 'enginetype', 'cylindernumber',
       'enginesize', 'fuelsystem', 'boreratio', 'stroke', 'compressionratio',
       'horsepower', 'peakrpm', 'citympg', 'highwaympg', 'price'],
      dtype='object')

In [204]:
final_data = pd.get_dummies(car_dataset, columns=[ 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation','enginetype',  'cylindernumber','fuelsystem'], drop_first = True)

In [205]:
final_data.describe()

        symboling   wheelbase  ...  fuelsystem_spdi  fuelsystem_spfi
count  205.000000  205.000000  ...       205.000000       205.000000
mean     0.834146   98.756585  ...         0.043902         0.004878
std      1.245307    6.021776  ...         0.205380         0.069843
min     -2.000000   86.600000  ...         0.000000         0.000000
25%      0.000000   94.500000  ...         0.000000         0.000000
50%      1.000000   97.000000  ...         0.000000         0.000000
75%      2.000000  102.400000  ...         0.000000         0.000000
max      3.000000  120.900000  ...         1.000000         1.000000

[8 rows x 190 columns]

In [206]:
final_data.head()

   symboling  wheelbase  ...  fuelsystem_spdi  fuelsystem_spfi
0          3       88.6  ...                0                0
1          3       88.6  ...                0                0
2          1       94.5  ...                0                0
3          2       99.8  ...                0                0
4          2       99.4  ...                0                0

[5 rows x 190 columns]

In [207]:
final_data.dtypes

symboling            int64
wheelbase          float64
carlength          float64
carwidth           float64
carheight          float64
                    ...
fuelsystem_idi       uint8
fuelsystem_mfi       uint8
fuelsystem_mpfi      uint8
fuelsystem_spdi      uint8
fuelsystem_spfi      uint8
Length: 190, dtype: object

In [208]:
np.random.seed(11111)
cx = np.random.rand(len(final_data)) < 0.72

train_sample = final_data[cx]
test_sample = final_data[~cx]

print(len(train_sample))
print(len(test_sample))

141
64

In [209]:
train_sample.head(10)

    symboling  wheelbase  ...  fuelsystem_spdi  fuelsystem_spfi
1           3       88.6  ...                0                0
2           1       94.5  ...                0                0
3           2       99.8  ...                0                0
4           2       99.4  ...                0                0
5           2       99.8  ...                0                0
6           1      105.8  ...                0                0
7           1      105.8  ...                0                0
8           1      105.8  ...                0                0
9           0       99.5  ...                0                0
11          0      101.2  ...                0                0

[10 rows x 190 columns]

In [210]:
train_sample.describe()

        symboling   wheelbase  ...  fuelsystem_spdi  fuelsystem_spfi
count  141.000000  141.000000  ...       141.000000       141.000000
mean     0.893617   98.692199  ...         0.035461         0.007092
std      1.228833    6.005665  ...         0.185601         0.084215
min     -1.000000   86.600000  ...         0.000000         0.000000
25%      0.000000   94.500000  ...         0.000000         0.000000
50%      1.000000   96.500000  ...         0.000000         0.000000
75%      2.000000  102.400000  ...         0.000000         0.000000
max      3.000000  115.600000  ...         1.000000         1.000000

[8 rows x 190 columns]

In [211]:
train_sample.dtypes

symboling            int64
wheelbase          float64
carlength          float64
carwidth           float64
carheight          float64
                    ...
fuelsystem_idi       uint8
fuelsystem_mfi       uint8
fuelsystem_mpfi      uint8
fuelsystem_spdi      uint8
fuelsystem_spfi      uint8
Length: 190, dtype: object

In [212]:
train_label0 = train_sample.loc[:,'price']
test_label0 = test_sample.loc[:,'price']

In [213]:
test_label0

0      13495.0
10     16430.0
14     24565.0
15     30760.0
18      5151.0
        ...
192    13845.0
193    12290.0
194    12940.0
196    15985.0
198    18420.0
Name: price, Length: 64, dtype: float64

In [214]:
train_data0 = train_sample.drop(columns=['price'])
test_data0 = test_sample.drop(columns=['price'])

In [215]:
test_data0

     symboling  wheelbase  ...  fuelsystem_spdi  fuelsystem_spfi
0            3       88.6  ...                0                0
10           2      101.2  ...                0                0
14           1      103.5  ...                0                0
15           0      103.5  ...                0                0
18           2       88.4  ...                0                0
..         ...        ...  ...              ...              ...
192          0      100.4  ...                0                0
193          0      100.4  ...                0                0
194         -2      104.3  ...                0                0
196         -2      104.3  ...                0                0
198         -2      104.3  ...                0                0

[64 rows x 189 columns]

In [216]:
test_data0.shape[1]

189

In [217]:
{train_data0.columns.get_loc(c): c for idx, c  in enumerate(train_data0.columns)}

{0: 'symboling',
 1: 'wheelbase',
 2: 'carlength',
 3: 'carwidth',
 4: 'carheight',
 5: 'curbweight',
 6: 'enginesize',
 7: 'boreratio',
 8: 'stroke',
 9: 'compressionratio',
 10: 'horsepower',
 11: 'peakrpm',
 12: 'citympg',
 13: 'highwaympg',
 14: 'CarName_alfa-romero Quadrifoglio',
 15: 'CarName_alfa-romero giulia',
 16: 'CarName_alfa-romero stelvio',
 17: 'CarName_audi 100 ls',
 18: 'CarName_audi 100ls',
 19: 'CarName_audi 4000',
 20: 'CarName_audi 5000',
 21: 'CarName_audi 5000s (diesel)',
 22: 'CarName_audi fox',
 23: 'CarName_bmw 320i',
 24: 'CarName_bmw x1',
 25: 'CarName_bmw x3',
 26: 'CarName_bmw x4',
 27: 'CarName_bmw x5',
 28: 'CarName_bmw z4',
 29: 'CarName_buick century',
 30: 'CarName_buick century luxus (sw)',
 31: 'CarName_buick century special',
 32: 'CarName_buick electra 225 custom',
 33: 'CarName_buick opel isuzu deluxe',
 34: 'CarName_buick regal sport coupe (turbo)',
 35: 'CarName_buick skyhawk',
 36: 'CarName_buick skylark',
 37: 'CarName_chevrolet impala',
 38: 'CarName_chevrolet monte carlo',
 39: 'CarName_chevrolet vega 2300',
 40: 'CarName_dodge challenger se',
 41: 'CarName_dodge colt (sw)',
 42: 'CarName_dodge colt hardtop',
 43: 'CarName_dodge coronet custom',
 44: 'CarName_dodge coronet custom (sw)',
 45: 'CarName_dodge d200',
 46: 'CarName_dodge dart custom',
 47: 'CarName_dodge monaco (sw)',
 48: 'CarName_dodge rampage',
 49: 'CarName_honda accord',
 50: 'CarName_honda accord cvcc',
 51: 'CarName_honda accord lx',
 52: 'CarName_honda civic',
 53: 'CarName_honda civic (auto)',
 54: 'CarName_honda civic 1300',
 55: 'CarName_honda civic 1500 gl',
 56: 'CarName_honda civic cvcc',
 57: 'CarName_honda prelude',
 58: 'CarName_isuzu D-Max ',
 59: 'CarName_isuzu D-Max V-Cross',
 60: 'CarName_isuzu MU-X',
 61: 'CarName_jaguar xf',
 62: 'CarName_jaguar xj',
 63: 'CarName_jaguar xk',
 64: 'CarName_maxda glc deluxe',
 65: 'CarName_maxda rx3',
 66: 'CarName_mazda 626',
 67: 'CarName_mazda glc',
 68: 'CarName_mazda glc 4',
 69: 'CarName_mazda glc custom',
 70: 'CarName_mazda glc custom l',
 71: 'CarName_mazda glc deluxe',
 72: 'CarName_mazda rx-4',
 73: 'CarName_mazda rx-7 gs',
 74: 'CarName_mazda rx2 coupe',
 75: 'CarName_mercury cougar',
 76: 'CarName_mitsubishi g4',
 77: 'CarName_mitsubishi lancer',
 78: 'CarName_mitsubishi mirage',
 79: 'CarName_mitsubishi mirage g4',
 80: 'CarName_mitsubishi montero',
 81: 'CarName_mitsubishi outlander',
 82: 'CarName_mitsubishi pajero',
 83: 'CarName_nissan clipper',
 84: 'CarName_nissan dayz',
 85: 'CarName_nissan fuga',
 86: 'CarName_nissan gt-r',
 87: 'CarName_nissan juke',
 88: 'CarName_nissan kicks',
 89: 'CarName_nissan latio',
 90: 'CarName_nissan leaf',
 91: 'CarName_nissan note',
 92: 'CarName_nissan nv200',
 93: 'CarName_nissan otti',
 94: 'CarName_nissan rogue',
 95: 'CarName_nissan teana',
 96: 'CarName_nissan titan',
 97: 'CarName_peugeot 304',
 98: 'CarName_peugeot 504',
 99: 'CarName_peugeot 504 (sw)',
 100: 'CarName_peugeot 505s turbo diesel',
 101: 'CarName_peugeot 604sl',
 102: 'CarName_plymouth cricket',
 103: 'CarName_plymouth duster',
 104: 'CarName_plymouth fury gran sedan',
 105: 'CarName_plymouth fury iii',
 106: 'CarName_plymouth satellite custom (sw)',
 107: 'CarName_plymouth valiant',
 108: 'CarName_porcshce panamera',
 109: 'CarName_porsche boxter',
 110: 'CarName_porsche cayenne',
 111: 'CarName_porsche macan',
 112: 'CarName_renault 12tl',
 113: 'CarName_renault 5 gtl',
 114: 'CarName_saab 99e',
 115: 'CarName_saab 99gle',
 116: 'CarName_saab 99le',
 117: 'CarName_subaru',
 118: 'CarName_subaru baja',
 119: 'CarName_subaru brz',
 120: 'CarName_subaru dl',
 121: 'CarName_subaru r1',
 122: 'CarName_subaru r2',
 123: 'CarName_subaru trezia',
 124: 'CarName_subaru tribeca',
 125: 'CarName_toyota carina',
 126: 'CarName_toyota celica gt',
 127: 'CarName_toyota celica gt liftback',
 128: 'CarName_toyota corolla',
 129: 'CarName_toyota corolla 1200',
 130: 'CarName_toyota corolla 1600 (sw)',
 131: 'CarName_toyota corolla liftback',
 132: 'CarName_toyota corolla tercel',
 133: 'CarName_toyota corona',
 134: 'CarName_toyota corona hardtop',
 135: 'CarName_toyota corona liftback',
 136: 'CarName_toyota corona mark ii',
 137: 'CarName_toyota cressida',
 138: 'CarName_toyota mark ii',
 139: 'CarName_toyota starlet',
 140: 'CarName_toyota tercel',
 141: 'CarName_toyouta tercel',
 142: 'CarName_vokswagen rabbit',
 143: 'CarName_volkswagen 1131 deluxe sedan',
 144: 'CarName_volkswagen 411 (sw)',
 145: 'CarName_volkswagen dasher',
 146: 'CarName_volkswagen model 111',
 147: 'CarName_volkswagen rabbit',
 148: 'CarName_volkswagen rabbit custom',
 149: 'CarName_volkswagen super beetle',
 150: 'CarName_volkswagen type 3',
 151: 'CarName_volvo 144ea',
 152: 'CarName_volvo 145e (sw)',
 153: 'CarName_volvo 244dl',
 154: 'CarName_volvo 245',
 155: 'CarName_volvo 246',
 156: 'CarName_volvo 264gl',
 157: 'CarName_volvo diesel',
 158: 'CarName_vw dasher',
 159: 'CarName_vw rabbit',
 160: 'fueltype_gas',
 161: 'aspiration_turbo',
 162: 'doornumber_two',
 163: 'carbody_hardtop',
 164: 'carbody_hatchback',
 165: 'carbody_sedan',
 166: 'carbody_wagon',
 167: 'drivewheel_fwd',
 168: 'drivewheel_rwd',
 169: 'enginelocation_rear',
 170: 'enginetype_dohcv',
 171: 'enginetype_l',
 172: 'enginetype_ohc',
 173: 'enginetype_ohcf',
 174: 'enginetype_ohcv',
 175: 'enginetype_rotor',
 176: 'cylindernumber_five',
 177: 'cylindernumber_four',
 178: 'cylindernumber_six',
 179: 'cylindernumber_three',
 180: 'cylindernumber_twelve',
 181: 'cylindernumber_two',
 182: 'fuelsystem_2bbl',
 183: 'fuelsystem_4bbl',
 184: 'fuelsystem_idi',
 185: 'fuelsystem_mfi',
 186: 'fuelsystem_mpfi',
 187: 'fuelsystem_spdi',
 188: 'fuelsystem_spfi'}

In [218]:
mean = train_data0.iloc[:,1:14].mean(axis=0)
train_data0.iloc[:,1:14] -= mean
std = train_data0.iloc[:,1:14].std(axis=0)
train_data0.iloc[:,1:14] /= std
test_data0.iloc[:,1:14] -= mean
test_data0.iloc[:,1:14] /= std

In [219]:
mean

wheelbase             98.692199
carlength            173.658156
carwidth              65.875887
carheight             53.648227
curbweight          2546.787234
enginesize           125.666667
boreratio              3.324184
stroke                 3.256809
compressionratio      10.070355
horsepower           103.702128
peakrpm             5143.971631
citympg               25.113475
highwaympg            30.581560
dtype: float64

In [220]:
std

wheelbase             6.005665
carlength            12.320089
carwidth              2.188604
carheight             2.508204
curbweight          529.769152
enginesize           41.733451
boreratio             0.266123
stroke                0.296387
compressionratio      3.868579
horsepower           38.424275
peakrpm             474.472458
citympg               6.509435
highwaympg            6.734937
dtype: float64

In [221]:
test_data0.describe()

       symboling  wheelbase  ...  fuelsystem_spdi  fuelsystem_spfi
count  64.000000  64.000000  ...        64.000000             64.0
mean    0.703125   0.034341  ...         0.062500              0.0
std     1.280869   1.016093  ...         0.243975              0.0
min    -2.000000  -1.713748  ...         0.000000              0.0
25%     0.000000  -0.498229  ...         0.000000              0.0
50%     0.500000  -0.240140  ...         0.000000              0.0
75%     2.000000   0.317667  ...         0.000000              0.0
max     3.000000   3.697809  ...         1.000000              0.0

[8 rows x 189 columns]

In [222]:
test_data0.head(10)

    symboling  wheelbase  ...  fuelsystem_spdi  fuelsystem_spfi
0           3  -1.680447  ...                0                0
10          2   0.417573  ...                0                0
14          1   0.800544  ...                0                0
15          0   0.800544  ...                0                0
18          2  -1.713748  ...                0                0
26          1  -0.831248  ...                0                0
27          1  -0.831248  ...                0                0
32          1  -0.831248  ...                0                0
34          1  -0.831248  ...                0                0
38          0  -0.365022  ...                0                0

[10 rows x 189 columns]

In [223]:
mean_label0 = train_label0.mean()
train_label0 -= mean_label0
std_label0 = train_label0.std()
train_label0 /= std_label0

test_label0 -= mean_label0
test_label0 /= std_label0

In [224]:
print(mean_label0)

13379.132390070921

In [225]:
std_label0

8189.4945680106175

In [226]:
train_data0.shape

(141, 189)

In [227]:
test_label0

0      0.014148
10     0.372534
14     1.365880
15     2.122337
18    -1.004718
         ...
192    0.056886
193   -0.132991
194   -0.053621
196    0.318196
198    0.615529
Name: price, Length: 64, dtype: float64

In [228]:
train_data1 = np.array(train_data0.iloc[:]).astype('float32')

test_data1 = np.array(test_data0.iloc[:]).astype('float32')

test_label1 = np.array(test_label0.astype('float32'))
train_label1 = np.array(train_label0.astype('float32'))

train_data1.shape
train_data1.dtype
train_data1.shape[1]

189

In [ ]:
#hidden layers including 10,8,6 unit & Output Layer with activation function relu/tanh/drop/regular

In [229]:
from keras import models
from keras import layers

def build_model(act):
  model0 = models.Sequential()
  model0.add(layers.Dense(128, activation=act, input_shape=(train_data1.shape[1],)))
  model0.add(layers.Dense(64, activation=act))
  model0.add(layers.Dense(32, activation=act))
  model0.add(layers.Dense(1))
  model0.compile(optimizer='rmsprop',loss='mse',metrics=['mae'])
  return model0

In [230]:
build_model('relu').summary()

Model: "sequential_44"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_176 (Dense)            (None, 128)               24320
_________________________________________________________________
dense_177 (Dense)            (None, 64)                8256
_________________________________________________________________
dense_178 (Dense)            (None, 32)                2080
_________________________________________________________________
dense_179 (Dense)            (None, 1)                 33
=================================================================
Total params: 34,689
Trainable params: 34,689
Non-trainable params: 0
_________________________________________________________________

In [231]:
build_model('tanh').summary()

Model: "sequential_45"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_180 (Dense)            (None, 128)               24320
_________________________________________________________________
dense_181 (Dense)            (None, 64)                8256
_________________________________________________________________
dense_182 (Dense)            (None, 32)                2080
_________________________________________________________________
dense_183 (Dense)            (None, 1)                 33
=================================================================
Total params: 34,689
Trainable params: 34,689
Non-trainable params: 0
_________________________________________________________________

In [232]:
from keras import  regularizers
def build_model_regular(act):
  model0 = models.Sequential()
  model0.add(layers.Dense(10, activation=act,kernel_regularizer=regularizers.l1_l2(l1=0.001, l2=0.001),input_shape=(train_data1.shape[1],)))
  model0.add(layers.Dense(8, activation=act,kernel_regularizer=regularizers.l1_l2(l1=0.001, l2=0.001)))
  model0.add(layers.Dense(6, activation=act,kernel_regularizer=regularizers.l1_l2(l1=0.001, l2=0.001)))
  model0.add(layers.Dense(1))
  model0.compile(optimizer='rmsprop',loss='mse',metrics=['mae'])
  return model0

In [233]:
build_model_regular('tanh').summary()

Model: "sequential_46"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_184 (Dense)            (None, 10)                1900
_________________________________________________________________
dense_185 (Dense)            (None, 8)                 88
_________________________________________________________________
dense_186 (Dense)            (None, 6)                 54
_________________________________________________________________
dense_187 (Dense)            (None, 1)                 7
=================================================================
Total params: 2,049
Trainable params: 2,049
Non-trainable params: 0
_________________________________________________________________

In [234]:
build_model_regular('relu').summary()

Model: "sequential_47"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_188 (Dense)            (None, 10)                1900
_________________________________________________________________
dense_189 (Dense)            (None, 8)                 88
_________________________________________________________________
dense_190 (Dense)            (None, 6)                 54
_________________________________________________________________
dense_191 (Dense)            (None, 1)                 7
=================================================================
Total params: 2,049
Trainable params: 2,049
Non-trainable params: 0
_________________________________________________________________

In [235]:

from keras import models
from keras import layers
def build_model_drop(act):
  model0 = models.Sequential()
  model0.add(layers.Dense(10, activation=act, input_shape=(train_data1.shape[1],)))
  model0.add(layers.Dropout(0.2))
  model0.add(layers.Dense(8, activation=act))
  model0.add(layers.Dropout(0.2))
  model0.add(layers.Dense(6, activation=act))
  model0.add(layers.Dropout(0.2))
  model0.add(layers.Dense(1))
  model0.compile(optimizer='rmsprop',loss='mse',metrics=['mae'])
  return model0

In [236]:
build_model_drop('tanh').summary()

Model: "sequential_48"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_192 (Dense)            (None, 10)                1900
_________________________________________________________________
dropout_36 (Dropout)         (None, 10)                0
_________________________________________________________________
dense_193 (Dense)            (None, 8)                 88
_________________________________________________________________
dropout_37 (Dropout)         (None, 8)                 0
_________________________________________________________________
dense_194 (Dense)            (None, 6)                 54
_________________________________________________________________
dropout_38 (Dropout)         (None, 6)                 0
_________________________________________________________________
dense_195 (Dense)            (None, 1)                 7
=================================================================
Total params: 2,049
Trainable params: 2,049
Non-trainable params: 0
_________________________________________________________________

In [237]:
build_model_drop('relu').summary()

Model: "sequential_49"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_196 (Dense)            (None, 10)                1900
_________________________________________________________________
dropout_39 (Dropout)         (None, 10)                0
_________________________________________________________________
dense_197 (Dense)            (None, 8)                 88
_________________________________________________________________
dropout_40 (Dropout)         (None, 8)                 0
_________________________________________________________________
dense_198 (Dense)            (None, 6)                 54
_________________________________________________________________
dropout_41 (Dropout)         (None, 6)                 0
_________________________________________________________________
dense_199 (Dense)            (None, 1)                 7
=================================================================
Total params: 2,049
Trainable params: 2,049
Non-trainable params: 0
_________________________________________________________________

In [ ]:
#Train the Model with Epochs (100)

In [238]:
#KFOLD validation tanh
import numpy as np
k = 4
num_val_samples = len(train_data1) // k
num_epochs = 100
all_scores_tanh = []

for i in range(k):
  print('processing fold #', i)

val_data = train_data1[i * num_val_samples: (i + 1) * num_val_samples]

val_targets = train_label1[i * num_val_samples: (i + 1) * num_val_samples]

partial_train_data = np.concatenate([train_data1[:i * num_val_samples], train_data1[(i + 1) * num_val_samples:]], axis=0)

partial_train_targets = np.concatenate([train_label1[:i * num_val_samples],train_label1[(i + 1) * num_val_samples:]],axis=0)


model = build_model('tanh')
model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=0)
val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)
all_scores_tanh.append(val_mae)

processing fold # 0
processing fold # 1
processing fold # 2
processing fold # 3
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7fed6cc08290> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

In [239]:
#KFOLD validation relu
import numpy as np
k = 4
num_val_samples = len(train_data1) // k
num_epochs = 100
all_scores_relu = []

for i in range(k):
  print('processing fold #', i)

val_data = train_data1[i * num_val_samples: (i + 1) * num_val_samples]

val_targets = train_label1[i * num_val_samples: (i + 1) * num_val_samples]

partial_train_data = np.concatenate([train_data1[:i * num_val_samples], train_data1[(i + 1) * num_val_samples:]], axis=0)

partial_train_targets = np.concatenate([train_label1[:i * num_val_samples],train_label1[(i + 1) * num_val_samples:]],axis=0)


model = build_model('relu')
model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=0)
val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)
all_scores_relu.append(val_mae)

processing fold # 0
processing fold # 1
processing fold # 2
processing fold # 3
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7fed67e4f440> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

In [240]:
#KFOLD validation regular
import numpy as np
k = 4
num_val_samples = len(train_data1) // k
num_epochs = 100
all_scores_regular = []

for i in range(k):
  print('processing fold #', i)

val_data = train_data1[i * num_val_samples: (i + 1) * num_val_samples]

val_targets = train_label1[i * num_val_samples: (i + 1) * num_val_samples]

partial_train_data = np.concatenate([train_data1[:i * num_val_samples], train_data1[(i + 1) * num_val_samples:]], axis=0)

partial_train_targets = np.concatenate([train_label1[:i * num_val_samples],train_label1[(i + 1) * num_val_samples:]],axis=0)


model = build_model_regular('relu')
model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=0)
val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)
all_scores_regular.append(val_mae)

processing fold # 0
processing fold # 1
processing fold # 2
processing fold # 3
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7fed67ed78c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

In [241]:
#KFOLD validation
import numpy as np
k = 4
num_val_samples = len(train_data1) // k
num_epochs = 100
all_scores_drop = []

for i in range(k):
  print('processing fold #', i)

val_data = train_data1[i * num_val_samples: (i + 1) * num_val_samples]

val_targets = train_label1[i * num_val_samples: (i + 1) * num_val_samples]

partial_train_data = np.concatenate([train_data1[:i * num_val_samples], train_data1[(i + 1) * num_val_samples:]], axis=0)

partial_train_targets = np.concatenate([train_label1[:i * num_val_samples],train_label1[(i + 1) * num_val_samples:]],axis=0)


model = build_model_drop('relu')
model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=0)
val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)
all_scores_drop.append(val_mae)

processing fold # 0
processing fold # 1
processing fold # 2
processing fold # 3
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7fed69987a70> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

In [241]:
#SCORES

In [242]:
all_scores_tanh

[0.2123998999595642]

In [243]:
all_scores_relu

[0.2908520996570587]

In [244]:
all_scores_regular

[0.2467559278011322]

In [245]:
all_scores_drop

[0.3201667368412018]

In [246]:
model_tanh = build_model('tanh')
model_tanh.fit(train_data1, train_label1, epochs=100, batch_size=1, verbose=0)
test_mse_score, test_mae_score = model_tanh.evaluate(test_data1, test_label1)

WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7fed6d54d170> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2/2 [==============================] - 0s 4ms/step - loss: 0.0912 - mae: 0.2420

In [247]:
model_relu = build_model('relu')
model_relu.fit(train_data1, train_label1, epochs=100, batch_size=1, verbose=0)
test_mse_score, test_mae_score = model_relu.evaluate(test_data1, test_label1)

WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7fed6d54d050> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2/2 [==============================] - 0s 8ms/step - loss: 0.0931 - mae: 0.2420

In [248]:
model_drop= build_model_drop('relu')
model_drop.fit(train_data1, train_label1, epochs=100, batch_size=1, verbose=0)
test_mse_score, test_mae_score = model_drop.evaluate(test_data1, test_label1)

WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7fed6e6adc20> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2/2 [==============================] - 0s 5ms/step - loss: 0.1462 - mae: 0.3013

In [249]:
model_regular = build_model_regular('relu')
model_regular.fit(train_data1, train_label1, epochs=100, batch_size=1, verbose=0)
test_mse_score, test_mae_score = model_regular.evaluate(test_data1, test_label1)

WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7fed67e86a70> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2/2 [==============================] - 0s 7ms/step - loss: 0.1325 - mae: 0.2317

In [250]:
test_label1

array([ 0.01414832,  0.3725343 ,  1.3658801 ,  2.122337  , -1.004718  ,
       -0.7045773 , -0.5886972 , -0.97443527, -0.763189  , -0.52312535,
       -0.05301089, -0.3704908 , -0.5449216 , -0.80397296, -0.5536523 ,
       -0.26059392,  0.6062484 ,  1.4864004 ,  2.5404336 ,  3.367835  ,
       -0.8779702 , -0.09159691,  0.18192424, -0.7802841 , -0.50065756,
       -0.9622245 , -0.6813769 , -0.5409531 ,  0.01463675,  0.12453365,
        0.46643507, -0.1806134 ,  0.2687428 ,  0.4299249 ,  0.45129374,
       -0.07511237,  2.3382235 ,  2.200547  , -0.49870384,  0.20280465,
        0.26019526, -0.68430746, -0.7224051 , -0.65524584, -0.98066276,
       -0.7889537 , -0.7547636 , -0.6888255 , -0.6277716 , -0.4983375 ,
       -0.6020069 , -0.4139611 , -0.22347318, -0.54107517,  0.28217462,
       -0.68430746, -0.6574438 , -0.59638995, -0.01027321,  0.056886  ,
       -0.1329914 , -0.05362143,  0.3181964 ,  0.6155285 ], dtype=float32)

In [ ]:
# FINAL PREDICTIONS

In [251]:
def predict(model,m):

  print(f'actual price was:{test_label1[m] * std_label0 + mean_label0}')
  return(f'predicted price :{(model.predict(test_data1[m:m+1].reshape(1,test_data1.shape[1]))) * std_label0 + mean_label0}')

In [252]:
x_tanh = predict(model_tanh,2)
x_tanh

actual price was:24565.000309357743
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7fed6880eef0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

'predicted price :[[20594.945]]'

In [255]:
x_relu = predict(model_relu,2)
x_relu

actual price was:24565.000309357743
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7fed6cbf7680> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

'predicted price :[[24742.574]]'

In [253]:
x_drop = predict(model_drop,2)
x_drop

actual price was:24565.000309357743
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7fed67e4f8c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

'predicted price :[[18984.06]]'

In [254]:
x_regular = predict(model_regular,2)
x_regular

actual price was:24565.000309357743
WARNING:tensorflow:11 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7fed6145a560> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

'predicted price :[[22424.055]]'